AppImage: add x86_64-v2 check
With #33101 we've had a report of a user saying the recent AppImages,
presumably those after #32431, do not work on their fairly old CPU, and
by "old" I mean only implements x86_64-v1.

Anaconda posted about changing the baseline for x86 packages from
x86_64-v1 to x86_64-v2 earlier this year on their primary package
channel:
https://www.anaconda.com/blog/updated-cpu-requirements-linux-recommendations-windows
As far as I could tell `conda-forge` hasn't announced the same, but the
fact someone ran into binary compatibility issues already means that
this decision leaked through some packages, or through our compile
options.

Add x86_64 version detection to the AppImage AppRun script, and prevent
launch with an explicit error message for the user.
If a graphical environment is available, GUI message/notification
commands are tried to show the error interactively.
These messages are translatable through bash's built-in gettext support,
though said translations aren't added to the Crowdin sync (yet).

German translation by @okh-mzny
Co-Authored-By: okh-mzny <60819623+okh-mzny@users.noreply.github.com>

diff --git a/package/bundle/linux/AppDir/AppRun b/package/bundle/linux/AppDir/AppRun
--- a/package/bundle/linux/AppDir/AppRun
+++ b/package/bundle/linux/AppDir/AppRun
@@ -1,8 +1,61 @@
 #!/bin/bash
+# This script has translatable strings. Extract them using:
+# bash --dump-po-strings AppRun > AppRun.pot
 set -eu
 
 HERE="$(dirname "$(readlink -f "${0}")")"
 export PREFIX="${HERE}/usr"
+
+# Do not export these variables!
+TEXTDOMAIN="AppRun"
+TEXTDOMAINDIR="${HERE}/locale"
+
+requirements_not_met() {
+    TITLE=$"FreeCAD launch error"
+    NOTMET=$"FreeCAD cannot run because the following requirements are not met:"
+    TEXT="${NOTMET}"$'\n'"${1}"
+    echo "${TEXT}" >&2
+    if [ -n "${DISPLAY:-}" ] || [ -n "${WAYLAND_DISPLAY:-}" ]; then
+        if command -v zenity >/dev/null 2>&1; then
+            zenity --error --text="${TEXT}" --title="${TITLE}" --icon-name="${HERE}/launch-error.svg"
+        elif command -v yad >/dev/null 2>&1; then
+            yad --text="${TEXT}" --title="${TITLE}" --image="${HERE}/launch-error.svg" --escape-ok
+        elif command -v kdialog >/dev/null 2>&1; then
+            kdialog --error "${TEXT}" --title "${TITLE}"
+        elif command -v notify-send >/dev/null 2>&1; then
+            notify-send -u normal -a FreeCAD -n "${HERE}/org.freecad.FreeCAD.svg" -i "${HERE}/launch-error.svg" "${TITLE}" "${TEXT}"
+        elif command -v gxmessage >/dev/null 2>&1; then
+            gxmessage "${TEXT}"
+        elif command -v xmessage >/dev/null 2>&1; then
+            xmessage "${TEXT}"
+        fi
+    fi
+    exit 127
+}
+
+# Check for CPU architecture version. x86 Conda has started requiring x86-64-v2:
+# https://www.anaconda.com/blog/updated-cpu-requirements-linux-recommendations-windows
+ARCH="$(uname -m)"
+if [ "${ARCH}" = x86_64 ]; then
+    # x86-64 architecture level detection from https://unix.stackexchange.com/a/631226
+    ARCHVER="$(awk -f- <<'EOF'
+BEGIN {
+    while (!/flags/) if (getline < "/proc/cpuinfo" != 1) exit 1
+    if (/lm/&&/cmov/&&/cx8/&&/fpu/&&/fxsr/&&/mmx/&&/syscall/&&/sse2/) level = 1
+    if (level == 1 && /cx16/&&/lahf/&&/popcnt/&&/sse4_1/&&/sse4_2/&&/ssse3/) level = 2
+    if (level == 2 && /avx/&&/avx2/&&/bmi1/&&/bmi2/&&/f16c/&&/fma/&&/abm/&&/movbe/&&/xsave/) level = 3
+    if (level == 3 && /avx512f/&&/avx512bw/&&/avx512cd/&&/avx512dq/&&/avx512vl/) level = 4
+    print level
+    exit 0
+}
+EOF
+)"
+    MIN_ARCHVER=2
+    if [ "${ARCHVER}" -lt "${MIN_ARCHVER}" ]; then
+        requirements_not_met $"Your computer's processor is too old (x86_64-v${ARCHVER}, minimum required is x86_64-v${MIN_ARCHVER})."
+    fi
+fi
+
 # export LD_LIBRARY_PATH="${HERE}/usr/lib${LD_LIBRARY_PATH:+':'}$LD_LIBRARY_PATH"
 export PYTHONHOME="${HERE}/usr"
 export PATH_TO_FREECAD_LIBDIR="${HERE}/usr/lib"
