[BUILD] enable sanity check

diff --git a/.github/workflows/cmake.yml b/.github/workflows/cmake.yml
--- a/.github/workflows/cmake.yml
+++ b/.github/workflows/cmake.yml
@@ -171,7 +171,7 @@ jobs:
         echo "::group::Run tests"
         xvfb-run --auto-servernum ${INSTALLED_APP_PATH} --console --run-test 0
         echo "::endgroup::"
-        #${INSTALLED_APP_PATH} --log-file /tmp/FreeCAD_installed.log &
-        #sleep 10 && pkill FreeCAD
-        #cat /tmp/FreeCAD_installed.log
-        #grep --file=../.log_errors /tmp/FreeCAD_installed.log ; [ $? == 1 ] && echo "No errors from .log_errors file found in the log after start from /usr/local/bin" || ( echo "Error from .log_errors found!" && false )
+        ${INSTALLED_APP_PATH} --log-file /tmp/FreeCAD_installed.log &
+        sleep 10 && pkill FreeCAD
+        cat /tmp/FreeCAD_installed.log
+        grep --file=../.log_errors /tmp/FreeCAD_installed.log ; [ $? == 1 ] && echo "No errors from .log_errors file found in the log after start from /usr/local/bin" || ( echo "Error from .log_errors found!" && false )
